"""
Shell utilities and command definitions
Provides command lists for terminal autocompletion and recognition
"""

from typing import List, Set

# Slash commands for XandAI CLI
SLASH_COMMANDS: List[str] = [
    "/task",
    "/review",
    "/agent",
    "/set-agent-limit",
    "/host",
    "/help",
    "/h",
    "/clear",
    "/cls",
    "/history",
    "/hist",
    "/context",
    "/ctx",
    "/status",
    "/stat",
    "/scan",
    "/structure",
    "/interactive",
    "/toggle",
    "/provider",
    "/providers",
    "/switch",
    "/detect",
    "/server",
    "/models",
    "/tools",
    "/exit",
    "/quit",
    "/bye",
]

# Commands that need directory suggestions
DIR_COMMANDS: List[str] = ["cd", "mkdir", "rmdir", "pushd", "popd"]

# Commands that need file suggestions
FILE_COMMANDS: List[str] = [
    "cat",
    "type",
    "nano",
    "vim",
    "edit",
    "open",
    "head",
    "tail",
    "less",
    "more",
]

# Commands that need both files and directories
PATH_COMMANDS: List[str] = [
    "ls",
    "dir",
    "cp",
    "copy",
    "mv",
    "move",
    "rm",
    "del",
    "find",
    "grep",
    "findstr",
    "tree",
    "du",
    "chmod",
    "chown",
    "stat",
]

# All terminal commands
TERMINAL_COMMANDS: List[str] = [
    # Sistema operacional básico
    "ls",
    "dir",
    "cd",
    "pwd",
    "cat",
    "type",
    "mkdir",
    "rmdir",
    "rm",
    "del",
    "uname",
    "whoami",
    "date",
    "time",
    "cls",
    "clear",
    "ls",
    "cp",
    "copy",
    "mv",
    "move",
    "ren",
    "rename",
    "find",
    "findstr",
    "grep",
    "ps",
    "tasklist",
    "kill",
    "taskkill",
    "ping",
    "tracert",
    "netstat",
    "ipconfig",
    "ifconfig",
    "echo",
    "tree",
    "which",
    "where",
    "date",
    "time",
    "cls",
    "clear",
    "help",
    "man",
    "history",
    "alias",
    # Python
    "python",
    "python3",
    "py",
    "pip",
    "pip3",
    "pipenv",
    "poetry",
    "conda",
    "mamba",
    "pyenv",
    "virtualenv",
    "venv",
    "activate",
    "deactivate",
    # JavaScript/Node.js
    "node",
    "npm",
    "yarn",
    "pnpm",
    "bun",
    "deno",
    "npx",
    "nvm",
    "fnm",
    # Java
    "java",
    "javac",
    "jar",
    "maven",
    "mvn",
    "gradle",
    "gradlew",
    "ant",
    # C/C++
    "gcc",
    "g++",
    "clang",
    "clang++",
    "make",
    "cmake",
    "ninja",
    # C#/.NET
    "dotnet",
    "csc",
    "msbuild",
    "nuget",
    # Go
    "go",
    "gofmt",
    "goimports",
    "mod",
    # Rust
    "rustc",
    "cargo",
    "rustup",
    "rustfmt",
    # Ruby
    "ruby",
    "gem",
    "bundle",
    "rails",
    "rake",
    "rbenv",
    "rvm",
    # PHP
    "php",
    "composer",
    "artisan",
    "phpunit",
    # Swift
    "swift",
    "swiftc",
    "xcodebuild",
    # Kotlin
    "kotlin",
    "kotlinc",
    # Scala
    "scala",
    "scalac",
    "sbt",
    # Lua
    "lua",
    "luac",
    # Perl
    "perl",
    "cpan",
    "cpanm",
    # R
    "r",
    "rscript",
    # Julia
    "julia",
    # Haskell
    "ghc",
    "ghci",
    "cabal",
    "stack",
    # Databases
    "mysql",
    "psql",
    "sqlite3",
    "mongo",
    "redis-cli",
    "sqlcmd",
    # DevOps e Cloud
    "docker",
    "kubectl",
    "helm",
    "terraform",
    "ansible",
    "aws",
    "az",
    "gcloud",
    "heroku",
    "vercel",
    "netlify",
    # Version Control
    "git",
    "svn",
    "hg",
    "bzr",
    # Build Tools
    "webpack",
    "vite",
    "rollup",
    "parcel",
    "esbuild",
    "tsc",
    "babel",
    "grunt",
    "gulp",
    "bower",
    # Linting e Testing
    "eslint",
    "prettier",
    "jest",
    "mocha",
    "karma",
    "cypress",
    "pytest",
    "unittest",
    "nose",
    "tox",
    # Editores de terminal
    "vim",
    "vi",
    "nvim",
    "nano",
    "emacs",
    "micro",
    "joe",
    # Monitoramento e Performance
    "top",
    "htop",
    "iotop",
    "vmstat",
    "iostat",
    "free",
    "df",
    "du",
    "nproc",
    "lscpu",
    "lsblk",
    "lsusb",
    "lspci",
    # Rede
    "curl",
    "wget",
    "ssh",
    "scp",
    "rsync",
    "ftp",
    "sftp",
    "nslookup",
    "dig",
    "host",
    "whois",
    # Compressão
    "tar",
    "zip",
    "unzip",
    "gzip",
    "gunzip",
    "7z",
    "rar",
    "unrar",
    # Text processing
    "sed",
    "awk",
    "sort",
    "uniq",
    "wc",
    "head",
    "tail",
    "cut",
    "tr",
    # Process management
    "nohup",
    "screen",
    "tmux",
    "systemctl",
    "service",
    "crontab",
    # Environment
    "env",
    "export",
    "set",
    "unset",
    "printenv",
    "source",
    # Permissions
    "chmod",
    "chown",
    "chgrp",
    "su",
    "sudo",
    "whoami",
    "id",
    # Archives and packages
    "apt",
    "apt-get",
    "yum",
    "dnf",
    "zypper",
    "pacman",
    "brew",
    "choco",
    "snap",
    "flatpak",
    "rpm",
    "dpkg",
]

# Terminal commands that are intercepted and run locally (Windows + Linux/macOS)
# This is a set for faster lookup during command interception
INTERCEPTED_COMMANDS: Set[str] = {
    # Directory/File listing
    "ls",
    "dir",
    # Navigation
    "pwd",
    "cd",
    # File operations
    "cat",
    "type",
    "head",
    "tail",
    "more",
    "less",
    "mkdir",
    "rmdir",
    "rm",
    "del",
    "erase",
    "cp",
    "copy",
    "mv",
    "move",
    "ren",
    "rename",
    # Search and text processing
    "find",
    "findstr",
    "grep",
    "wc",
    "sort",
    "uniq",
    # System info
    "ps",
    "tasklist",
    "top",
    "df",
    "du",
    "free",
    "uname",
    "whoami",
    "date",
    "time",
    "systeminfo",
    "ver",
    "hostname",
    # Network
    "ping",
    "tracert",
    "traceroute",
    "netstat",
    "ipconfig",
    "ifconfig",
    # Process management
    "kill",
    "taskkill",
    "killall",
    # File attributes
    "chmod",
    "chown",
    "attrib",
    "icacls",
    # Utilities
    "echo",
    "which",
    "where",
    "whereis",
    "tree",
    "file",
    # Clear screen
    "clear",
    "cls",
    # Help
    "help",
    "man",
    # ===== COMANDOS DE DESENVOLVIMENTO ADICIONADOS =====
    # Python
    "python",
    "python3",
    "py",
    "pip",
    "pip3",
    "pipenv",
    "poetry",
    "conda",
    "mamba",
    "pyenv",
    "virtualenv",
    "venv",
    "activate",
    "deactivate",
    # JavaScript/Node.js
    "node",
    "npm",
    "yarn",
    "pnpm",
    "bun",
    "deno",
    "npx",
    "nvm",
    "fnm",
    # Java
    "java",
    "javac",
    "jar",
    "maven",
    "mvn",
    "gradle",
    "gradlew",
    "ant",
    # C/C++
    "gcc",
    "g++",
    "clang",
    "clang++",
    "make",
    "cmake",
    "ninja",
    # C#/.NET
    "dotnet",
    "csc",
    "msbuild",
    "nuget",
    # Go
    "go",
    "gofmt",
    "goimports",
    "mod",
    # Rust
    "rustc",
    "cargo",
    "rustup",
    "rustfmt",
    # Ruby
    "ruby",
    "gem",
    "bundle",
    "rails",
    "rake",
    "rbenv",
    "rvm",
    # PHP
    "php",
    "composer",
    "artisan",
    "phpunit",
    # Git and version control
    "git",
    "hg",
    "svn",
    "bzr",
    # Text editors
    "nano",
    "vim",
    "emacs",
    "vi",
    "code",
    "cursor",
    "notepad",
    # Container and deployment
    "docker",
    "podman",
    "kubectl",
    "helm",
    "terraform",
    "vagrant",
    # Network tools
    "curl",
    "wget",
    "ssh",
    "scp",
    "rsync",
    "nc",
    "telnet",
    "nmap",
    # Archive tools
    "tar",
    "gzip",
    "gunzip",
    "zip",
    "unzip",
    "rar",
    "unrar",
    "7z",
}
